name: Docker Core Build and Push

on:
  pull_request:
    branches: [ "develop" ]
    paths:
      - "now-waypoint-core/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./now-waypoint-core

      - name: Setup environment variables
        run: |
          echo "CLOUD_AWS_CREDENTIALS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "CLOUD_AWS_CREDENTIALS_SECRET_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "FILE_STORAGE_PATH=/app/static/files" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./now-waypoint-core

      - name: List files in build/libs
        run: ls -R build/libs
        working-directory: ./now-waypoint-core

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./now-waypoint-core
          file: ./now-waypoint-core/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/now-waypoint-core:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            CLOUD_AWS_CREDENTIALS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY_ID }}
            CLOUD_AWS_CREDENTIALS_SECRET_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}

      - name: Save Core GITHUB_SHA
        run: echo ${{ github.sha }} > core_sha.txt

      - name: Upload Core SHA file
        uses: actions/upload-artifact@v4
        with:
          name: core_sha
          path: core_sha.txt
